name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'

      - name: Checkout Code
        uses: actions/checkout@v4
       
      
      - name: Build Protoc Docker container
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: protoc.dockerfile
          tags: tinkar-schema-protoc:latest

      - name: Generate Java Code
        run: |
          docker run -v ./src/main/java-generated:/home/proto-builder/src/main/java-generated --rm tinkar-schema-protoc:latest
      
      - name: list java code
        run: |
          ls src/main/java-generated

      - name: Build IKMDEV Code
        if: github.event.repository.name != 'github_actions_test'
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
          sonarcloud_organization: ${{ github.repository_owner }}
          sonarcloud_sources: ${{ 'src/main/java' }}
          sonarcloud_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          sonarcloud_coverage_jacoco_xmlReportPaths: ${{ 'target/site/jacoco/jacoco.xml' }}
          sonarcloud_java_binaries: ${{ 'target/classes' }}
          sonarcloud_tests: ${{ 'src/test/java' }}

    
